name: update demo

on:
  workflow_dispatch:

env:
  CLICOLOR_FORCE: "1"

jobs:
  update-demo:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: go.mod

      # to install ttyd and ffmpeg
      - uses: charmbracelet/vhs-action@59641cdc7fadf3978db65eb8c6937ea2752f4ec3 # v2.1.0
        with:
          version: v0.4.0 # NOTE: https://github.com/charmbracelet/vhs-action/issues/137
          path: ./tapes/cli/demo.tape
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: update cli gif
        run: |
          for t in ./tapes/cli/*; do
            vhs < $t
          done
      - name: update library gif
        run: |
          for t in ./tapes/library/*; do
            vhs < $t
          done

      - uses: peter-evans/create-pull-request@c5a7806660adbe173f04e3e038b0ccdcd758773c # v6.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: update docs
          body: ${{ github.sha }}
          branch: docs/update
          branch-suffix: short-commit-hash
